---
name: YAML Lint

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'deploy/**/*.yaml'
      - 'deploy/**/*.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'
